kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster-a
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        dns:
          type: CoreDNS
          imageRepository: registry.k8s.io/coredns
          imageTag: v1.12.2
  - role: worker
  - role: worker
networking:
  serviceSubnet: "10.21.0.0/16"
  podSubnet: "10.20.0.0/16"
